### ISSUE TITLE
How to add liquid blocks like lava or sea to my mod?

### ISSUE THREAD

**Issue by huiwy** [Anuken/ExampleMod#10]

**Comment by huiwy** [comment]
This is my current code, and I cannot find the block after I import the mod.
{
    "type" : "Floor",
    "name" : "sea",
    "speedMultiplier" : 0.75,
    "variants" : 0,
    "status" : "wet",
    "statusDuration" : 60,
    "liquilDrop" : "water",
    "isLiquid" : true,
    "cacheLayer" : "water"
}

**Comment by ThatOneBepis** [comment]
in order to find a block in editor, it MUST have a sprite first
