### ISSUE TITLE
Optional ingredients

### ISSUE THREAD

**Issue by tmetzger** [Anuken/ExampleMod#12]
Hey guys! Trying to make a mod. We want to create a block that takes various kinds of input, like the steam generator can accept coal or spore pods, and output power. We've tried a few ways of settings up the JSON file, but no luck. Items in parallel are all required. Make sense?

Any suggestions or hints?

**Comment by Anuken** [comment]
There isn't really any way to do so without using an existing type of generator. The steam/thorium generators work by looking at each item's flammability/radioactivity and accepting/producing power based on that. There currently is no way to do that with arbitrary items.

**Comment by tmetzger** [comment]
OK thanks for the reply!

Tom Metzger, CEO
www.groupanizer.com
Facebook <http://www.facebook.com/groupanizer> | Twitter
<http://www.twitter.com/groupanizer>
