### ISSUE TITLE
bullets?

### ISSUE THREAD

**Issue by MegaLP** [Anuken/ExampleMod#13]
is it possible to add custom bullets to units not those ones who are already in the game new self made bullets for units? if yes how?

**Comment by What42Pizza** [comment]
This might be able to help you: https://simonwoodburyforget.github.io/mindustry-modding
If that doesn't help then you could ask your question again on the modding discord channel here: https://discordapp.com/channels/391020510269669376/631946157496729620

**Comment by MegaLP** [comment]
thanks you helped me but i want somewhat an example because i am not the pro im programming

**Comment by MegaLP** [comment]
well i found out you need to define the bullet by the unit/mech
