### ISSUE TITLE
How to create map in Mod

### ISSUE THREAD

**Issue by MishaLion** [Anuken/ExampleMod#18]
Tell me how to create a map in the mod or how to add it there . because I don't understand .

**Comment by What42Pizza** [comment]
I'm not exactly sure but you can ask for help on the modding discord here: https://discordapp.com/channels/391020510269669376/631946157496729620

**Comment by Vortetty** [comment]
@MishaLion to add maps, go make a map in the editor, export the map file, then place it in "modname/maps/" then make it a zone by modifying "[content/zones/silvercrags.json](https://github.com/Anuken/ExampleMod/blob/master/content/zones/silver-crags.json "silvercrags.json")", it will have all of the basic map info, the filename minus .json will be the zone id so you can use it for zone requirements.
