### ISSUE TITLE
stray blue pixel

### ISSUE THREAD

**Issue by What42Pizza** [Anuken/ExampleMod#19]
In the png file for electrum there is a single blue pixel and I don't think it's supposed to be there. I noticed it while making a texture for a mod and being that electrum is a golden color I think it is a leftover from the titanium texture.

**Comment by Vortetty** [comment]
@What42Pizza i have made a fixed image, just need @Anuken to put it in the file.
![electrum fixed](https://user-images.githubusercontent.com/33466216/68884126-5c003f00-06c7-11ea-8043-dfc2e6d981ed.png)

**Comment by Anuken** [comment]
See my response to #42
