### ISSUE TITLE
how did we add new bootser for turret

### ISSUE THREAD

**Issue by galyfray** [Anuken/ExampleMod#33]
after a while looking inside the mindustry code i did this inside the turret's code of my mod 
```json
"consumes": {
		"items": {
			"booster" : true,
			"inaccuracy" : 0,
            "items": [
				{ "item": "phase-fabric", "amount": 1 }
			]
		}
	},
```
then the phase fabric is a booster but it did nothing . how do i add boost effect ?

**Comment by Anuken** [comment]
You can't. Turrets do not support custom boosters.
