### ISSUE TITLE
Custom Main Menu logo

### ISSUE THREAD

**Issue by Vortetty** [Anuken/ExampleMod#36]
i have tried replacing the main menu logo when my mod is loaded. is this possible?

here is my mod: https://github.com/Vortetty/Mindustryalization/blob/master/sprites/ui/logo.png

i even overwrote ui/logo yet it does not replace it, is this possible in the scope of a mod?

**Comment by Anuken** [comment]
Please ask in the #modding-general channel on Discord for modding help. This tracker is really supposed to be for reporting issues with the example mod.

**Comment by Vortetty** [comment]
@Anuken I would have asked there, but as I am not allowed to have a discord, i can't ask on the discord.
