### ISSUE TITLE
Texture noise with conveyors

### ISSUE THREAD

**Issue by MEEPofFaith** [Anuken/ExampleMod#42]
On the curved conveyors (1-#) and straight conveyors (0-#), there's some noise in the textures. For the curved ones, it's the bottom-left corner, and the straight ones, it's the center belt part.

**Comment by Anuken** [comment]
That does look ugly, but the textures themselves are very ugly anyway, and there's no sense fixing the sprites when they'll get removed anyway.

**Comment by MEEPofFaith** [comment]
oh no
