### ISSUE TITLE
Problems happening with unit factories

### ISSUE THREAD

**Issue by Syncinus** [Anuken/ExampleMod#48]
So I've been making a mod, in which I have added multiple new unit factories, and the "top" texture is rendered improperly. 
![image](https://user-images.githubusercontent.com/34169172/80893786-acc61d00-8c92-11ea-9b17-e70e030d6601.png) 
This is what textures look like (It's a recolor of Fortress/Titan factory)
![image](https://user-images.githubusercontent.com/34169172/80893791-bbaccf80-8c92-11ea-8f8b-53df621f9751.png)
And that is what they should look like.
It appears an outline of sort is appearing around the top part, as it looks way sharper then it should and doesn't seem to blend properly.

**Comment by GlennFolker** [comment]
Every mod unit factory looks like that

**Comment by MEEPofFaith** [comment]
Turn off Linear Filtering in the settings.

**Comment by Anuken** [comment]
Addressed in the main repo.
