### ISSUE TITLE
Where to find methods for scripts?

### ISSUE THREAD

**Issue by gnorbsl** [Anuken/ExampleMod#49]
In the script example for the silo you see methods like tile.entity.cons and so on. Where can I find what methods/variables are available for an object?

Aside from that, how do I get data like player positions?

And is it possible to play a sound in a specific volume all across the map independent of the player distance?

**Comment by Anuken** [comment]
There is no documentation or class reference, so the best you (could) do is look at the Mindustry source code - except that now 6.0 is in development, all of that is outdated and will no longer be functional. If you have specific questions about scripting, you should ask in the Mindustry Discord.

Until 6.0 is released, I would discourage making script-based mods.
