### ISSUE TITLE
Is there any explain in the mod example?

### ISSUE THREAD

**Issue by qwesdfok** [Anuken/ExampleMod#5]
Or create a template.json to describe what the meaning of the attribute.
For example, what does "power" mean, what does "category" mean, how many the valid "category" tags in the game, what the meaning of the "electrum-drill.png", "electrum-drill-rim.png", "electrum-drill-rotator.png" and "electrum-drill-top.png" in the sprites folder.

So we can use the template.json to create new blocks and need not read the source code.

Thanks.

**Comment by werlucad** [comment]
This is just an example, if you want it explained go to https://mindustrygame.github.io/wiki/modding/

**Comment by qwesdfok** [comment]
But on the web, there is no detail in the attribute of JSON files.  For example, how to know the output speed of a custom drill based on the "drillTime" attribute?  How to calculate the true speed of the conveyor? In the example, the speed=0.12 means 0.12*150=18 item/s, but there is no document. So I was wondering if there is a plan to complete a coding document?

**Comment by Anuken** [comment]
Yes. [See this issue.](https://github.com/Anuken/Mindustry/issues/809)

I don't have the time to write modding documentation myself at the moment.
