### ISSUE TITLE
Breaksound not playing/Debugging mods?

### ISSUE THREAD

**Issue by gnorbsl** [Anuken/ExampleMod#50]
Is there a way to debug mods? I have created a block with breaksound: alarm and a file named alarm.ogg in sounds, for whatever reason the sound stopped playing after the second or thirs install of the mod directly from github.

Are there any logs?

This is the example:
https://github.com/gnorbsl/ExampleMod

**Comment by Anuken** [comment]
> Is there a way to debug mods

Yes, `print("text")` and the console accessed with `F8`.

> for whatever reason the sound stopped playing

Sounds like an issue that was fixed in the latest version. Make sure you're on 104.10.

The issue tracker is for problems with this particularly mod; you should ask questions about modding in the Discord.
