### ISSUE TITLE
Unlocked block in example mod

### ISSUE THREAD

**Issue by tmateer** [Anuken/ExampleMod#60]
I have played the example mod and I believe unlocked all of the items in the Tech Tree.
However, when you go to the Core Database, it shows one unlocked block.
It is after Message (which is the last unlocked block in the original game)
and before the Chrome Wraith Factory.  All of the blocks in the Example mod appear to be
in alphabetical order.  So either there is some other block beginning with ABC
that I am missing or else there might be an indexing issue with the new blocks
(something like the new blocks start with index 1 and there is nothing to fill
the index 0 place).  I'm just guessing there.  Anyway, I believe there is some kind of
gap between the blocks of the original game and this mod which makes it appear that
there is an unlocked block which I don't think is really part of the tech tree.

**Comment by Anuken** [comment]
This mod won't be updated, and V6 has a different tech tree system.

**Comment by tmateer** [comment]
Are you able to verify that there is an unlocked block in the mod that doesn't belong there or did I miss a step in researching the technologies?

**Comment by tmateer** [comment]
Also, do you have any information on V6 like when it will be available?
I had not heard of that before, but I am new to this game.

**Comment by Anuken** [comment]
I don't have a release date, and there's no sense verifying anything when this mod will be scrapped anyway.
