### ISSUE TITLE
Golden Sand not showing up in examine map

### ISSUE THREAD

**Issue by Shidub** [Anuken/ExampleMod#8]
I realize this is not intended to be a full mod, but since it is trying to show the different things it seems that this is missing. It has the silver ore that can be mined by player or drilled. But there are no generated or placed areas with the golden sand to obtain the gold powder to actually see the other example stuff in action. Also when you updated the mod to 2.0 you forgot to edit the mod.json to say as such. I'm going to look into how to fix this myself tomorrow if I get a chance but something you may want to resolve so the example is more complete to show the differences between ore block and mine able floor.

**Comment by Anuken** [comment]
This mod doesn't have a 2.0 version. Are you referring to the releases page? That's only there to show a message that you **shouldn't** use that page.
