### ISSUE TITLE
Reactor example?

### ISSUE THREAD

**Issue by Serdjio3** [Anuken/ExampleMod#9]
I want to create a new reactor for my mod. But there is no any example reactors. I need a help.(maybe type? Or how to make any new power generator explode if dont connect cryofluid into it? like thorium)

**Comment by Serdjio3** [comment]
And is it possible to make a factory, which have 2 or above items in output? Like a separator.

**Comment by sean-gribben** [comment]
If you have any questions, normally you can find a good template [here](https://github.com/Anuken/Mindustry/blob/master/core/src/io/anuke/mindustry/content/Blocks.java) 
Like for example [here](https://github.com/Anuken/Mindustry/blob/master/core/src/io/anuke/mindustry/content/Blocks.java#L1142) shows how you would format an impact reactor. Then, just base all your json off that
